language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarqube:
    organization: "cpollet-github"
    token:
      secure: $SONARQUBE_TOKEN

install: true

script:
 - mvn clean package
 - mvn -P sonar-java org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

notifications:
  email:
    - $NOTIFICATION_EMAIL

branches:
  only:
    - master